### PR TITLE
Fix katakana and hiragana search interchangeability

### LINKED ISSUE #64: [BUG][SP][PC][SEARCH] Kanji/hiragana/katakana search for costume
Add kanji/ katakana/ hiragana search for costume.

### PR DESCRIPTION
**Pull request by AsukaCHikaru**
Parse char code in decimal then check if it's in the range for katakana for `keywordSearch` and `photoCostume`. If true return string from its char code - 96. (the difference between hiragana and katakana in decimal unicode for same letter)
This fixes #64 .

### CODE REVIEW

File: src/services/apis/parseGanaCode.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export const parseKatakanaToHiragana = oriStr => {
+  return oriStr
+    .split("")
+    .map(letter => {
+      const code10 = letter.charCodeAt(0);
+      return code10 > 12448 && code10 < 12543 // Unicode range for Katakana
```
Comment (dwi2) [inline src/services/apis/parseGanaCode.js]: Personally, I'd suggest writing `12448` and `12543` as constants to increase readability.
For example,
```js
const KATAKANA_START = 12448;
const KATAKANA_END = 12543;
// ...
const codeUnit = letter.charCodeAt(0);
return codeUnit > KATAKANA_START && codeUnit < KATAKANA_END
```

So that you don't have to write comments because the code explains itself.

File: src/services/apis/parseGanaCode.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+        ? String.fromCharCode(code10 - 96) // Difference between Hiragana and Katakana in decimal for same letter
```
Comment (dwi2) [inline src/services/apis/parseGanaCode.js]: ditto

File: src/services/apis/parseGanaCode.js (hunk 1 above)
Comment (AsukaCHikaru) [reply src/services/apis/parseGanaCode.js]: Very cool, will do
